
version: '3'

volumes:
  db_data: {}

services:
  dbpostgresql:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/mysql
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: '1'
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  config-server:
    image: config-server:latest
    environment:
      PROFILE: native
      MEM_ARGS:   "-Xmx320m"     
            
  discovery-server:
    image: discovery-server:latest
    environment:
      PROFILE: native
      MEM_ARGS:   "-Xmx320m"     
            
  gateway:
    image: gateway:latest
    depends_on:
      - config-server
      - discovery-server
      - dbpostgresql
    ports:
      - 9999:9999
    environment:
      PROFILE: docker
      MEM_ARGS:   "-Xmx320m"  