
version: '3'
services:
  config-server:
        image: config-server:latest
        environment:
            PROFILE: native
            MEM_ARGS:   "-Xmx320m"     
            
  discovery-server:
        image: discovery-server:latest
        environment:
            PROFILE: native
            MEM_ARGS:   "-Xmx320m"     
            
  gateway:
        image: gateway:latest
        depends_on:
        - config-server
        - discovery-server
        ports:
        - 9999:9999
        environment:
            PROFILE: docker
            MEM_ARGS:   "-Xmx320m"  