server:
  port: 9999
  #authentication 
  security: 
    user:      
      name: root 
      password: secret
      
security:
  jwt:
    token:
      secret-key: apple
      expiration:  10 * 60 * 1000 #10 mins