server:
  port: 9999
      
security:
  jwt:
    token:
      secret-key: apple
      expiration: 600000 #10 mins
      
spring:
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/db
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create